# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Hemanth Pasula"
resume_title:                   "Senior Software Engineer (open to work)"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "hemanthreddy996669@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "623-276-7734"
resume_contact_address:         "Arizona, United States"

resume_header_contact_info:     "1221 E Broadway Rd, Tempe, 85282, Arizona • United States• hemanthreddy996669@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p> 
I am Hemanth Pasula, a results-driven professional with a passion for technology and a track record of academic and professional excellence. Currently pursuing my Masters in Computer Science at Arizona State University, I have honed my skills in software development, data engineering, and project management. With a solid foundation in programming languages such as Java, Python, and C++, coupled with expertise in technologies like MuleSoft, SQL, and AWS, I have excelled in roles such as MuleSoft Developer at Capgemini, India, where I optimized API development processes, achieved significant time savings, and collaborated on high-impact projects. My commitment to innovation extends beyond the workplace, as evidenced by my involvement in cutting-edge research projects, leadership roles in organizing hackathons and workshops, and a continuous pursuit of certifications to stay at the forefront of industry trends. As I continue to navigate the dynamic landscape of technology, I am driven by a relentless pursuit of excellence and a passion for making meaningful contributions to the field.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
#resume_social_links:
  #resume_github_url:            "https://github.com/HEMANTH996669"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
#resume_print_social_links:      false

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
